### ISSUE TITLE
Help: Problem install under Mac-os:big-sur

### ISSUE THREAD

**Issue by JamieYJQ** [aewallin/randompolygon#2]
Hello, here is the error occurred when I was installing under Mac OS Big-sur 2:
$ sudo make
_**[ 33%] Built target librandompolygon
[ 66%] Built target librandompolygon_static
[ 83%] Linking CXX shared module randompolygon.so
Undefined symbols for architecture arm64:
  "_PyFloat_FromDouble", referenced from:
      boost::python::converter::arg_to_python<double>::arg_to_python(double const&) in rpg_py.cpp.o
  "_PyList_Type", referenced from:
      boost::python::converter::pyobject_type<boost::python::list, &(PyList_Type)>::get_pytype() in rpg_py.cpp.o
  "_PyString_FromStringAndSize", referenced from:
      boost::python::to_python_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in rpg_py.cpp.o
  "_PyString_Type", referenced from:
      boost::python::to_python_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::get_pytype() const in rpg_py.cpp.o
  "__Py_NoneStruct", referenced from:
      boost::python::api::object::object() in rpg_py.cpp.o
  "boost::python::detail::init_module(char const*, void (*)())", referenced from:
      _initrandompolygon in rpg_py.cpp.o
ld: symbol(s) not found for architecture arm64**_
If you saw this issue, help please.Thx.

**Comment by aewallin** [comment]
can you post the output of the cmake configuration step on your platform?
FWIW, below the output I get on ubuntu. In particular the **boost-python** library version might be the issue?

the warnings listed below could be fixed, but they are probably not the cause of your problem.

randompolygon/bld$ cmake ../src
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
-- USING CXXFLAGS = '-g -O2 -fdebug-prefix-map=/build/cgal-ZyilPF/cgal-4.11=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -frounding-math -O3 -DNDEBUG'
-- USING EXEFLAGS = '-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed '
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGAL_TweakFindBoost.cmake:44 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CGAL_Boost_USE_STATIC_LIBS'.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/CGAL/UseCGAL.cmake:23 (include)
  CMakeLists.txt:7 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Requested component: Core
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.48") found components: thread system chrono date_time atomic 
-- Requested component: MPFR
-- Requested component: GMPXX
-- Requested component: GMP
-- Found Git: /usr/bin/git (found version "2.20.1") 
-- version_string.cmake git set GIT_COMMIT_ID: 11.12-17-g2df57db
**-- Found Boost: /usr/include (found version "1.65.1") found components: python** 
**-- Boost_LIB_VERSION: 1_65_1**
-- Boost_INCLUDE_DIRS are: /usr/include
-- Boost_PYTHON_LIBRARY is: /usr/lib/x86_64-linux-gnu/libboost_python.so
-- boost_LIBRARY_DIRS is: /usr/lib/x86_64-linux-gnu
-- Boost_LIBRARIES is: /usr/lib/x86_64-linux-gnu/libboost_python.so
-- Python module will be installed to: /usr/local/lib/python2.7/dist-packages
-- CMAKE_INSTALL_PREFIX is : /usr/local
-- Python libraries will be installed to: lib/python2.7/dist-packages
-- DEB_ARCHITECTURE is: amd64
-- package_details.cmake called with SRC_DIR is = 
-- package_details.cmake called with version  = 11.12.17
CMake Warning (dev) at deb/package_details.cmake:5 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:162 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- package_details.cmake CMAKE_SOURCE_DIR is = /home/anders/Desktop/randompolygon/src
-- package_details.cmake descr file = /home/anders/Desktop/randompolygon/src/deb/debian_package_description.txt
--  'make' builds the c++ library and the python module
--  'make package' builds a binary DEB package
--  'make spackage' builds a source DEB package
--  'make install' installs
-- Configuring done
CMake Warning (dev) at CMakeLists.txt:86 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "version_string" of target "librandompolygon_static"
  does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:74 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "version_string" of target "librandompolygon" does
  not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:100 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "version_string" of target "randompolygon" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done

**Comment by JamieYJQ** [comment]
Thanks for your answer! But now I have setup under Ubuntu instead of Mac.
